## ---------------------------
##
## Script name: AMPLIFICATION PLOTTER MODULE
##
## Purpose of script:
##
## Author: jorgedelpozolerida
##
## Date Created: 2020-12-14
##
## Email: jorge.delpozo@qiagen.com / jorgedelpozolerida@gmail.com
##
## ---------------------------
##
## Notes:
##   
##
## ---------------------------
##
#' TO DO:
#' 
#' 


# User Interface --------------------------------------------------------------


#' Amplification Plotter module user interface
#'
#' @param id, character used to specify namespace, see \code{shiny::\link[shiny]{NS}}
#'
#' @return a \code{shiny::\link[shiny]{tagList}} containing UI elements


mod_amplificationPlotterUI <- function(id) {
  
  ns <- NS(id)
  
  tagList(
    plotOutput(ns("plot1"), height = "875px") 
  )
}


# Server --------------------------------------------------------------



#' Amplification Plotter module server-side processing
#'
#' @param input, output, session standard \code{shiny} boilerplate
#' @param id, Character used to specify namespace, see \code{shiny::\link[shiny]{NS}}
#' @param data, Data frame containing RC|Cycle|S0:S5|qPCRTemp|
#' @param selected_chamber, list generated by chamberSelector module with following components
#' \describe{
#'   \item{CH_xtalk}{reactive character vector with selected sensors where
#'   to apply cross-talk}
#'   \item{CH}{reactive character vector with selected sensors}
#'   \item{RC}{reactive character vector with selected reaction chambers}
#'   \item{faceting}{reactive character string indicating whether to apply faceting}
#'   
#'

mod_amplificationPlotterServer <- function(id, data_r, selected_chambers_r, current_testID) {
  moduleServer(
    id,
    function(input, output, session) {
      
      # ---------------------- DATA PROCESSING ---------------------------------
      datap_r <- reactive({
        data_r() %>% # data is passed as reactive and must be extracted
          mutate(RC = as.character(RC)) %>%
          gather(
            key = Sensor, # make data tidy
            value = Fluorescence,
            -RC, -Cycle, -qPCRTemp, -testID
          ) %>%
          filter(RC %in% selected_chambers_r$RC_r(), Sensor %in% selected_chambers_r$CH_r()) %>%
          unite("RC_Sensor", c(RC, Sensor), remove = FALSE) %>% #useful for plot labels
          mutate(RC_Sensor = paste0("RC", RC_Sensor) ) %>% 
          unite("ID_RC_Sensor", c(testID, RC_Sensor), remove = FALSE) 
          
      })
      
      # ----------------------  PLOT CREATION ----------------------------------
      
      plot1_obj_r <- reactive({
        plot1 <- datap_r() %>%
          func_amplificationplot(
            title = paste0(
              "Amplification plot for RC ", paste0(selected_chambers_r$RC_r(), collapse = ", "),
              ", Sensor ", paste0((selected_chambers_r$CH_r()), collapse = ", ")
            ),
            xlabel = "Cycle number", ylabel = "Fluorescence level",
            current_testID = current_testID,
            faceting = selected_chambers_r$faceting_r() #controlled by this boolean variable
          )
        return(plot1)
      })
      # --------------------------  OUTPUTS ------------------------------------
      
      output$plot1 <- renderPlot({
        plot1_obj_r()
      })
    }
  )
}